name: test-selenium
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@v2
      - 
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - 
        name: Install Package
        run: |
          pip install -r requirements.txt
      - 
        name: Test Selenium
        run: python test_selenium.py
      - name: Commit files
        run: |
          git config --local user.email "super.pylori6@gmail.com"
          git config --local user.name "super-pylori"
          git add .
          git commit -m "Update numbers3.csv" -a
          git push origin master